### ISSUE TITLE
stationID

### ISSUE THREAD

**Issue by prinzenrico** [ChristianGeie/MMM-PublicTransportVVO#4]
Hallo,
I use your module with the stationID: 33000733 (Südhöhe), but only ever the information of the stationID: 33000037 (Postplatz) are shown. Can you help me? Thanks

**Comment by ChristianGeie** [comment]
i double checked the stationID and i can confirm it (33000733). I think, the issue is somewhere else. The "Postplatz" stationID is default (https://github.com/ChristianGeie/MMM-PublicTransportVVO/blob/master/MMM-PublicTransportVVO.js#L7), if no other stationID is provided. Are you sure that your config in `config/config.js` is correct?

**Comment by prinzenrico** [comment]
Thanks for the answer the config.js should be correct. My config.js is attached to this mail.

Gesendet von Mail für Windows

Von: ChristianGeie
Gesendet: Dienstag, 7. September 2021 18:20
An: ChristianGeie/MMM-PublicTransportVVO
Cc: prinzenrico; Author
Betreff: Re: [ChristianGeie/MMM-PublicTransportVVO] stationID (#4)

i double checked the stationID and i can confirm it (33000733). I think, the issue is somewhere else. The "Postplatz" stationID is default (https://github.com/ChristianGeie/MMM-PublicTransportVVO/blob/master/MMM-PublicTransportVVO.js#L7), if no other stationID is provided. Are you sure that your config in config/config.js is correct?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 


/* Magic Mirror Config Sample
 *
 * By Michael Teeuw https://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information on how you can configure this file
 * see https://docs.magicmirror.builders/getting-started/configuration.html#general
 * and https://docs.magicmirror.builders/modules/configuration.html
 */
let config = {
	address: "localhost", 	// Address to listen on, can be:
							// - "localhost", "127.0.0.1", "::1" to listen on loopback interface
							// - another specific IPv4/6 to listen on a specific interface
							// - "0.0.0.0", "::" to listen on any interface
							// Default, when address config is left out or empty, is "localhost"
	port: 8080,
	basePath: "/", 	// The URL path where MagicMirror is hosted. If you are using a Reverse proxy
					// you must set the sub path here. basePath must end with a /
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], 	// Set [] to allow all IP addresses
															// or add a specific IPv4 of 192.168.1.5 :
															// ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
															// or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
															// ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	useHttps: false, 		// Support HTTPS or not, default "false" will use HTTP
	httpsPrivateKey: "", 	// HTTPS private key path, only require when useHttps is true
	httpsCertificate: "", 	// HTTPS Certificate path, only require when useHttps is true

	language: "de",
	locale: "en-US",
	logLevel: ["INFO", "LOG", "WARN", "ERROR"], // Add "DEBUG" for even more logging
	timeFormat: 24,
	units: "metric",
	// serverOnly:  true/false/"local" ,
	// local for armv6l processors, default
	//   starts serveronly and then starts chrome browser
	// false, default for all NON-armv6l devices
	// true, force serveronly mode, because you want to.. no UI on this device

	modules: [
		{
			module: "Alert",
			position:"button_left",
		},
		//{
		  //  module: "MMM-Fuel",
			//position:"button_left",
			//config:{
			//api_key:"3c08d3e4-e575-ca1a-3acb-f1f56b2f0a1",
			//lat:51.020172,
			//lng:13.733177,
			//types:["diesel"],
			//}	
		//},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "calendar",
			header: "Meine Termine",
			position: "top_left",
			config: {
				calendars: [
					{
						symbol: "calendar-check",
						url: "https://calendar.google.com/calendar/ical/erik-franke%40gmx.de/private-17f3875422ff4c42c5fb04004bb138aa/basic.ics"					}
				]
			}
		},
		//{
			//module: "compliments",
			//position: "lower_third",
		//},
		{
			module: "helloworld",
			position: "top_bar",
			config: {
				    text:"<div class='medium' style='color:red'>Es gibt keine religiösen Kinder, es gibt nur Kinder religiöser Eltern</div>"
				}
		},
		{
			module: "weather",
			position: "top_right",
			config: {
				weatherProvider: "openweathermap",
				type: "current",
				location: "Dresden",
				locationID: "2935022", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				apiKey: "bed7f54b4747e8cca9128d4565230087"
			}
		},
		{
			module: "weather",
			position: "top_right",
			header: "Weather Forecast",
			config: {
				weatherProvider: "openweathermap",
				type: "forecast",
				location: "Dresden",
				locationID: "2935022", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				apiKey: "bed7f54b4747e8cca9128d4565230087"
			}
		},
		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "ARD",
						//url: "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml"
						url: "http://www.tagesschau.de/xml/rss2"
					}
				],
				showSourceTitle: true,
				showPublishDate: true,
				broadcastNewsFeeds: true,
				broadcastNewsUpdates: true
			}
		},
		{
			module: "MMM-ImagesPhotos",
			position: "middle_center",
			config: {
					opacity: 0.9,
					animationSpeed: 500,
					updateInterval: 50000,
					maxWidth: "35%",
					maxHeight: "35%"
				}
		},
		{
			module: "MMM-PublicTransportVVO",
			position: "bottom_left",
			coinfig: {
				stationId: 33000733,
				hidden: false,
				delay: 0,
				updateInterval: 120000,
				marqueeLongDirections: false,
				showTableHeaders: true,
				showTableHeadersAsSymbols: true,
			}
		},
		{
			module: "MMM-Jast",
			position: "bottom_right",
			config: {
				    maxWidth: "100%",
				    updateIntervallInSeconds: 300,
				    fadeSpeedInSeconds: 3.5,
				    scroll: "vertical",
				    useGrouping: false,
				    currencyStyle: "code",
				    showColors: true,
				    showCurrency: true,
				    showChangePercent: true,
				    showChangeValue: false,
				    showChangeValueCurrency: false,
				    showPortfolioValue: false,
				    showPortfolioGrowthPercent: false,
				    showPortfolioGrowth: false,
				    numberDecimalsValues: 2,
				    numberDecimalsPercentages: 1,
				    virtualHorizontalMultiplier: 2,
				    stocks: [
						{ name: "DAIMLER", symbol: "DAI.DE" },
						{ name: "RTL", symbol: "RRTL.DE" },
						{ name: "URANIUM", symbol: "1WM.F" },
						{ name: "DEUTSCHE PFANDBRIEFBANK", symbol: "PBB.DE" }
					]
			}
		}
	]
};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

**Comment by ChristianGeie** [comment]
json error - hard to find:
`showTableHeadersAsSymbols: true,`
the comma invalids the whole config, remove it from the JSON object 
same for this typo:
`coinfig: {`
wrong JSON object name

**Comment by prinzenrico** [comment]
Many thanks for your help. Sorry the write fault error in coinfig I had find it myself.
The module runs with comma too. Again thanks for the nice module and your trouble.  

Gesendet von Mail für Windows

Von: ChristianGeie
Gesendet: Montag, 13. September 2021 11:33
An: ChristianGeie/MMM-PublicTransportVVO
Cc: prinzenrico; Author
Betreff: Re: [ChristianGeie/MMM-PublicTransportVVO] stationID (#4)

json error - hard to find:
showTableHeadersAsSymbols: true,
the comma invalids the whole config, remove it from the JSON object
same for this typo:
coinfig: {
wrong JSON object name
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
